import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/candidates">CANDIDATES</Link>
        </li>
        <li>
          <Link to="/addnewjob">ADDNEWJOB</Link>
        </li>
        <li>
          <Link to="/jobs">JOBS</Link>
        </li>
        <li>
          <Link to="/dashboard">DASHBOARD</Link>
        </li>
        <li>
          <Link to="/jobsone">JOBSOne</Link>
        </li>
        <li>
          <Link to="/frame126">Frame126</Link>
        </li>
        <li>
          <Link to="/frame126one">Frame126One</Link>
        </li>
        <li>
          <Link to="/dashboardone">DASHBOARDOne</Link>
        </li>
        <li>
          <Link to="/companyonboarding">CompanyOnboarding</Link>
        </li>
        <li>
          <Link to="/frame128">Frame128</Link>
        </li>
        <li>
          <Link to="/jobstwo">JOBSTwo</Link>
        </li>
        <li>
          <Link to="/company">Company</Link>
        </li>
        <li>
          <Link to="/icons">Icons</Link>
        </li>
        <li>
          <Link to="/addnewjobone">ADDNEWJOBOne</Link>
        </li>
        <li>
          <Link to="/jobsthree">JOBSThree</Link>
        </li>
        <li>
          <Link to="/candidatesone">CANDIDATESOne</Link>
        </li>
        <li>
          <Link to="/settings">Settings</Link>
        </li>
        <li>
          <Link to="/selectmultiplecandidate">SelectMultipleCandidate</Link>
        </li>
        <li>
          <Link to="/frame126two">Frame126Two</Link>
        </li>
        <li>
          <Link to="/candidateonboardingsignup">CandidateOnboardingSignup</Link>
        </li>
        <li>
          <Link to="/jobsfour">JOBSFour</Link>
        </li>
        <li>
          <Link to="/frame125">Frame125</Link>
        </li>
        <li>
          <Link to="/addnewjobtwo">ADDNEWJOBTwo</Link>
        </li>
        <li>
          <Link to="/addnewjobthree">ADDNEWJOBThree</Link>
        </li>
        <li>
          <Link to="/assets">Assets</Link>
        </li>
        <li>
          <Link to="/resumebank">ResumeBank</Link>
        </li>
        <li>
          <Link to="/dashboardtwo">DASHBOARDTwo</Link>
        </li>
        <li>
          <Link to="/frame121">Frame121</Link>
        </li>
        <li>
          <Link to="/candidatestwo">CANDIDATESTwo</Link>
        </li>
        <li>
          <Link to="/resumebankone">ResumeBankOne</Link>
        </li>
        <li>
          <Link to="/candidate">Candidate</Link>
        </li>
        <li>
          <Link to="/frame120">Frame120</Link>
        </li>
        <li>
          <Link to="/addnewjobfour">ADDNEWJOBFour</Link>
        </li>
        <li>
          <Link to="/companyonboardingone">CompanyonboardingOne</Link>
        </li>
        <li>
          <Link to="/dashboardthree">DASHBOARDThree</Link>
        </li>
        <li>
          <Link to="/dashboardfour">DASHBOARDFour</Link>
        </li>
        <li>
          <Link to="/macbookpro16two">MacBookPro16Two</Link>
        </li>
        <li>
          <Link to="/frame129">Frame129</Link>
        </li>
        <li>
          <Link to="/resumebanktwo">ResumeBankTwo</Link>
        </li>
        <li>
          <Link to="/addnewjobfive">ADDNEWJOBFive</Link>
        </li>
        <li>
          <Link to="/jobsfive">JOBSFive</Link>
        </li>
        <li>
          <Link to="/frame121one">Frame121One</Link>
        </li>
        <li>
          <Link to="/jobssix">JOBSSix</Link>
        </li>
        <li>
          <Link to="/resumebankthree">ResumeBankThree</Link>
        </li>
        <li>
          <Link to="/addnewjobsix">ADDNEWJOBSix</Link>
        </li>
        <li>
          <Link to="/frame170">Frame170</Link>
        </li>
        <li>
          <Link to="/resumebankfour">ResumeBankFour</Link>
        </li>
        <li>
          <Link to="/frame128one">Frame128One</Link>
        </li>
        <li>
          <Link to="/jobsseven">JOBSSeven</Link>
        </li>
        <li>
          <Link to="/dashboardfive">DASHBOARDFive</Link>
        </li>
        <li>
          <Link to="/resumebankfive">ResumeBankFive</Link>
        </li>
        <li>
          <Link to="/dashboardsix">DASHBOARDSix</Link>
        </li>
        <li>
          <Link to="/dashboardseven">DASHBOARDSeven</Link>
        </li>
        <li>
          <Link to="/candidatesthree">CANDIDATESThree</Link>
        </li>
        <li>
          <Link to="/macbookpro16one">MacBookPro16One</Link>
        </li>
        <li>
          <Link to="/iconsone">IconsOne</Link>
        </li>
        <li>
          <Link to="/dashboardcloned">DASHBOARDcloned</Link>
        </li>
        <li>
          <Link to="/resumebanksix">ResumeBankSix</Link>
        </li>
        <li>
          <Link to="/createajob">Createajob</Link>
        </li>
        <li>
          <Link to="/dashboardclonedone">DASHBOARDclonedOne</Link>
        </li>
        <li>
          <Link to="/homepage">Homepage</Link>
        </li>
        <li>
          <Link to="/frame170one">Frame170One</Link>
        </li>
        <li>
          <Link to="/aboutpage">Aboutpage</Link>
        </li>
        <li>
          <Link to="/candidateone">CandidateOne</Link>
        </li>
        <li>
          <Link to="/jobseight">JOBSEight</Link>
        </li>
        <li>
          <Link to="/companyonboardingtwo">CompanyOnboardingTwo</Link>
        </li>
        <li>
          <Link to="/testlibrary">TESTLIBRARY</Link>
        </li>
        <li>
          <Link to="/jobcreation">JobCreation</Link>
        </li>
        <li>
          <Link to="/resumebankseven">ResumeBankSeven</Link>
        </li>
        <li>
          <Link to="/jobcreationone">JobCreationOne</Link>
        </li>
        <li>
          <Link to="/companyonboardingthree">CompanyonboardingThree</Link>
        </li>
        <li>
          <Link to="/jobsnine">JOBSNine</Link>
        </li>
        <li>
          <Link to="/dashboardeight">DASHBOARDEight</Link>
        </li>
        <li>
          <Link to="/addingacandidate">Addingacandidate</Link>
        </li>
        <li>
          <Link to="/resumebankeight">ResumeBankEight</Link>
        </li>
        <li>
          <Link to="/resumebanknine">ResumeBankNine</Link>
        </li>
        <li>
          <Link to="/jobcreationtwo">JobCreationTwo</Link>
        </li>
        <li>
          <Link to="/candidateview">CandidateView</Link>
        </li>
        <li>
          <Link to="/frame126three">Frame126Three</Link>
        </li>
        <li>
          <Link to="/dashboardpages">Dashboardpages</Link>
        </li>
        <li>
          <Link to="/jobsten">JOBSTen</Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
